version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb-vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
  redis:
    image: redis:7.0.11-alpine
    restart: "no"
    ports:
      - '6379:6379'
    command: redis-server --save 30 1 --loglevel warning --requirepass pass
    volumes:
      - redisvol:/data


volumes:
  mongodb-vol:
  redisvol: